### ISSUE TITLE
json2typescript v.0.9.5 produces compile errors when "strict": true compiler option is used

### ISSUE THREAD

**Issue by DRepinSLB** [dhlab-basel/json2typescript#17] opened 2017-06-30 14:26 UTC
When a consuming project uses the tsc compiler option "strict": true, one observes a number of compiler errors originating in json2typescript:
![image](https://user-images.githubusercontent.com/25776179/27740009-2b42d23a-5d76-11e7-858f-80c3bd2aa817.png)

**Comment by andreas-aeschlimann** [comment] 2017-07-19 01:33
The current version runs well with strict mode, so I'm wondering whether this is due to your setup or due to the old commit. Do you have a minimal example to reproduce this?

**Comment by andreas-aeschlimann** [comment] 2017-09-10 12:20
As mentioned in #23 I think it is fixed with the current version (1.0.3). Please let me know if this is not the case.

**Closed by andreas-aeschlimann** 2017-09-10 12:20 UTC
Labels: help wanted

**Comment by lookfirst** [comment] 2017-09-11 04:47
@andreas-aeschlimann Same as #23. Has nothing to do with strict mode... TypeScript always produces good JS. This is a compiler issue.
