### ISSUE TITLE
Feature request: serialize by class

### ISSUE THREAD

**Issue by Messier82** [dhlab-basel/json2typescript#4] opened 2017-02-28 13:22 UTC
Hi! I really liked this library and just wondered, can we, developers, have slightly improved serialize function, so it can accept a class same way, as deserialize method receives it? Thank you!

**Comment by andreas-aeschlimann** [comment] 2017-02-28 23:48
Serializing an object is basically just calling `JSON.stringify(instance)`. I have implemented that as follows:

```
let instance = {
     id: 1,
     name: "Andreas"
}; // test object instance
let jsonString: string = JsonConvert.serializeObject(instance);
```

Or did you mean something else?

**Comment by andreas-aeschlimann** [comment] 2017-04-02 00:24
Closing due to inactivity. Will reopen if really an issue.

**Comment by Messier82** [comment] 2017-04-19 10:58
I meant to serialize and rename all parameters, how they're defined by JsonProperty in the class itself

**Comment by andreas-aeschlimann** [comment] 2017-04-20 12:20
I don't follow, can you please make an example and explain what you mean? Maybe you mean something similar like #6?

**Comment by Messier82** [comment] 2017-04-20 12:46
No. For example: we have some class, described to use JsonConvert. It have 3 params: _id, _name, _age and JsonProperty is set up to deserialize them from id, name and age(without underscores) attributes. It's working like a charm. But I want to SERIALIZE them and in output have properties, that I described by JsonProperties(id, name, age), not original ones(_id, _name, _age)

**Comment by andreas-aeschlimann** [comment] 2017-04-20 19:40
Basically you have this scenario:

JSON:
_id, _name, _age

TypeScript:
id, name, age

The deserialization maps _id to id, _name to name and _age to age.

Am I correct you would like the serialize() function to map id to _id, name to _name and age to _age again, as it was in the JSON?

**Comment by Messier82** [comment] 2017-04-24 08:14
Exactly!

**Comment by andreas-aeschlimann** [comment] 2017-04-24 11:42
Ok, I will keep this issue open and put it on my to do list for a future version.

**Comment by Messier82** [comment] 2017-04-25 08:32
Thank you!

**Comment by RAHILKHERA** [comment] 2017-05-30 08:01
Waiting for this enhancement.

**Comment by andreas-aeschlimann** [comment] 2017-05-30 23:38
@RAHILKHERA I will work on this after finishing my current project in around 2 weeks!

**Comment by RAHILKHERA** [comment] 2017-05-31 03:52
@andreas-aeschlimann Thanks a lot. Please comment here whenever it is ready.

**Comment by HeWhoHasNoName** [comment] 2017-06-05 03:41
@RAHILKHERA looking forward to this feature as I was curious about it not being implemented myself... as generally in the java world (being a java dev) this is what I was expecting.  Thanks and look forward to see the update.

**Comment by crownofapollo** [comment] 2017-06-20 15:36
Adding my request for this feature as well. Coming from the C# world, this was my expected behavior.

**Comment by bmercier-manakin** [comment] 2017-06-30 09:43
+1

**Comment by raviada** [comment] 2017-07-13 01:16
+1
@Messier82, how did you solve this in the meanwhile? I have a fairly large and nested JSON which works great for deserializing into TypeScript objects. But my problem is now I have to save it to saver, and the APIs expect the json keys to have underscores instead of camecase.

please let me know if you used any alternatives to solve it temporarily until this feature is available. This is almost like Jackson libraries in Java world.

**Comment by andreas-aeschlimann** [comment] 2017-07-16 23:00
I'll close this as this is implemented now. Will publish the NPM package when the other features are included as well.

**Closed by andreas-aeschlimann** 2017-07-16 23:00 UTC
Labels: enhancement
